import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import Home from "@/app/components/Home/Home"
// import About from '@/app/components/About/About'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Home/> */}
        {/* <About/> */}
        {children}</body>
    </html>
  )
}
